/**
 * Casa Dam — Datos mock-up del catálogo de productos
 * Catálogo digital de revestimientos, porcelanato, cerámicas y materiales de construcción
 */

const TASAS_CAMBIO = {
  usd: 1,
  cop: 4200,
  ves: 36.50
};

const PRODUCTOS = [
  {
    id: "prod-001",
    codigo_interno: "231060",
    nombre: "LÍBANO GRIS",
    descripcion_larga: "Porcelanato de gran formato inspirado en piedra natural libanesa. Ideal para pisos de alto tránsito en interiores y exteriores. Acabado mate de fácil mantenimiento y alta resistencia al desgaste.",
    categoria: "Porcelanato",
    subcategoria: "Mate",
    ancho: 60,
    largo: 120,
    espesor: 0.9,
    unidad_medida: "cm",
    color: "Gris",
    acabado: "Mate",
    material: "Porcelanato",
    uso: "Ambos",
    marca: "Lamosa",
    m2_por_caja: 1.44,
    piezas_por_caja: 2,
    peso: 32.5,
    precio_usd: 18.90,
    mostrar_precio: true,
    disponible: true,
    destacado: true,
    imagenes: [
      { url: "https://placehold.co/800x800/f5f0eb/4a4a4a?text=L%C3%ADbano+Gris", es_principal: true }
    ]
  },
  {
    id: "prod-002",
    codigo_interno: "231061",
    nombre: "LÍBANO BEIGE",
    descripcion_larga: "Versión en tono beige del porcelanato Líbano. Acabado mate con textura suave que replica la piedra caliza natural. Perfecto para espacios residenciales y comerciales de estilo mediterráneo.",
    categoria: "Porcelanato",
    subcategoria: "Mate",
    ancho: 60,
    largo: 120,
    espesor: 0.9,
    unidad_medida: "cm",
    color: "Beige",
    acabado: "Mate",
    material: "Porcelanato",
    uso: "Ambos",
    marca: "Lamosa",
    m2_por_caja: 1.44,
    piezas_por_caja: 2,
    peso: 32.5,
    precio_usd: 18.90,
    mostrar_precio: true,
    disponible: true,
    destacado: false,
    imagenes: [
      { url: "https://placehold.co/800x800/f5f0eb/4a4a4a?text=L%C3%ADbano+Beige", es_principal: true }
    ]
  },
  {
    id: "prod-003",
    codigo_interno: "241210",
    nombre: "CARRARA PULIDO",
    descripcion_larga: "Porcelanato de acabado pulido con veteado tipo mármol Carrara. Brillo excepcional y superficie reflectiva. Recomendado para pisos interiores, salas y recibidores de alto impacto visual.",
    categoria: "Porcelanato",
    subcategoria: "Pulido",
    ancho: 80,
    largo: 80,
    espesor: 1.0,
    unidad_medida: "cm",
    color: "Blanco",
    acabado: "Pulido",
    material: "Porcelanato",
    uso: "Piso",
    marca: "Vitromex",
    m2_por_caja: 1.92,
    piezas_por_caja: 3,
    peso: 42.0,
    precio_usd: 22.50,
    mostrar_precio: true,
    disponible: true,
    destacado: true,
    imagenes: [
      { url: "https://placehold.co/800x800/fafafa/4a4a4a?text=Carrara+Pulido", es_principal: true }
    ]
  },
  {
    id: "prod-004",
    codigo_interno: "241215",
    nombre: "CALACATA ORO",
    descripcion_larga: "Porcelanato pulido de lujo con vetas doradas sobre fondo blanco. Inspirado en el mármol Calacatta italiano. Cada pieza es única en su veteado. Ideal para baños, cocinas y vestíbulos.",
    categoria: "Porcelanato",
    subcategoria: "Pulido",
    ancho: 60,
    largo: 120,
    espesor: 0.9,
    unidad_medida: "cm",
    color: "Blanco",
    acabado: "Pulido",
    material: "Porcelanato",
    uso: "Pared",
    marca: "EuroCeramic",
    m2_por_caja: 1.44,
    piezas_por_caja: 2,
    peso: 33.0,
    precio_usd: 27.35,
    mostrar_precio: true,
    disponible: true,
    destacado: true,
    imagenes: [
      { url: "https://placehold.co/800x800/fff8ec/4a4a4a?text=Calacata+Oro", es_principal: true }
    ]
  },
  {
    id: "prod-005",
    codigo_interno: "231070",
    nombre: "TRAVERTINO MARFIL",
    descripcion_larga: "Porcelanato rectificado con diseño de travertino en tono marfil. Superficie mate con microtextura que imita los poros de la piedra natural. Antideslizante, apto para zonas húmedas.",
    categoria: "Porcelanato",
    subcategoria: "Rectificado",
    ancho: 19.3,
    largo: 118.4,
    espesor: 1.14,
    unidad_medida: "cm",
    color: "Crema",
    acabado: "Rectificado",
    material: "Porcelanato",
    uso: "Ambos",
    marca: "Incefa",
    m2_por_caja: 1.37,
    piezas_por_caja: 6,
    peso: 30.8,
    precio_usd: 23.65,
    mostrar_precio: true,
    disponible: false,
    destacado: false,
    imagenes: [
      { url: "https://placehold.co/800x800/faf5ef/4a4a4a?text=Travertino+Marfil", es_principal: true }
    ]
  },
  {
    id: "prod-006",
    codigo_interno: "251320",
    nombre: "MADERA ROBLE NATURAL",
    descripcion_larga: "Porcelanato efecto madera de roble en formato tablón. Textura y veta realistas con acabado mate. Calidez visual de la madera con la durabilidad del porcelanato. No se raya ni absorbe humedad.",
    categoria: "Porcelanato",
    subcategoria: "Mate",
    ancho: 20,
    largo: 120,
    espesor: 0.9,
    unidad_medida: "cm",
    color: "Madera Natural",
    acabado: "Mate",
    material: "Porcelanato",
    uso: "Piso",
    marca: "Lamosa",
    m2_por_caja: 1.44,
    piezas_por_caja: 6,
    peso: 28.5,
    precio_usd: 19.80,
    mostrar_precio: true,
    disponible: true,
    destacado: false,
    imagenes: [
      { url: "https://placehold.co/800x800/ede0d4/4a4a4a?text=Madera+Roble", es_principal: true }
    ]
  },
  {
    id: "prod-007",
    codigo_interno: "251325",
    nombre: "MADERA NOGAL OSCURO",
    descripcion_larga: "Porcelanato efecto madera de nogal en tono marrón oscuro. Formato tablón de 20x120 cm. Ideal para crear ambientes elegantes y acogedores. Compatible con calefacción radiante.",
    categoria: "Porcelanato",
    subcategoria: "Mate",
    ancho: 20,
    largo: 120,
    espesor: 0.9,
    unidad_medida: "cm",
    color: "Marrón",
    acabado: "Mate",
    material: "Porcelanato",
    uso: "Piso",
    marca: "Lamosa",
    m2_por_caja: 1.44,
    piezas_por_caja: 6,
    peso: 28.5,
    precio_usd: 19.80,
    mostrar_precio: false,
    disponible: true,
    destacado: false,
    imagenes: [
      { url: "https://placehold.co/800x800/5c3a21/e8e8e8?text=Madera+Nogal", es_principal: true }
    ]
  },
  {
    id: "prod-008",
    codigo_interno: "231080",
    nombre: "CEMENTO PULIDO GRIS",
    descripcion_larga: "Porcelanato de acabado satinado con efecto cemento pulido en tono gris medio. Estética industrial contemporánea. Bordes rectificados para junta mínima de 1.5 mm.",
    categoria: "Porcelanato",
    subcategoria: "Satinado",
    ancho: 60,
    largo: 60,
    espesor: 0.95,
    unidad_medida: "cm",
    color: "Gris",
    acabado: "Satinado",
    material: "Porcelanato",
    uso: "Ambos",
    marca: "Vitromex",
    m2_por_caja: 1.44,
    piezas_por_caja: 4,
    peso: 31.0,
    precio_usd: 15.50,
    mostrar_precio: true,
    disponible: true,
    destacado: false,
    imagenes: [
      { url: "https://placehold.co/800x800/b0b0b0/ffffff?text=Cemento+Pulido", es_principal: true }
    ]
  },
  {
    id: "prod-009",
    codigo_interno: "231081",
    nombre: "CEMENTO PULIDO HUESO",
    descripcion_larga: "Variante en tono hueso del porcelanato cemento pulido. Superficie satinada que refleja la luz sutilmente. Ideal para espacios minimalistas y escandinavos.",
    categoria: "Porcelanato",
    subcategoria: "Satinado",
    ancho: 60,
    largo: 60,
    espesor: 0.95,
    unidad_medida: "cm",
    color: "Hueso",
    acabado: "Satinado",
    material: "Porcelanato",
    uso: "Ambos",
    marca: "Vitromex",
    m2_por_caja: 1.44,
    piezas_por_caja: 4,
    peso: 31.0,
    precio_usd: 15.50,
    mostrar_precio: true,
    disponible: true,
    destacado: false,
    imagenes: [
      { url: "https://placehold.co/800x800/e8e0d8/4a4a4a?text=Cemento+Hueso", es_principal: true }
    ]
  },
  {
    id: "prod-010",
    codigo_interno: "251400",
    nombre: "MÁRMOL ESTATUARIO",
    descripcion_larga: "Porcelanato de gran formato con diseño de mármol Estatutario. Fondo blanco puro con vetas grises dramáticas. Acabado pulido de alto brillo para un efecto de lujo inigualable.",
    categoria: "Porcelanato",
    subcategoria: "Pulido",
    ancho: 120,
    largo: 120,
    espesor: 1.2,
    unidad_medida: "cm",
    color: "Blanco",
    acabado: "Pulido",
    material: "Porcelanato",
    uso: "Ambos",
    marca: "EuroCeramic",
    m2_por_caja: 1.44,
    piezas_por_caja: 1,
    peso: 38.0,
    precio_usd: 35.00,
    mostrar_precio: true,
    disponible: true,
    destacado: true,
    imagenes: [
      { url: "https://placehold.co/800x800/fcfcfc/4a4a4a?text=M%C3%A1rmol+Estatuario", es_principal: true }
    ]
  },
  {
    id: "prod-011",
    codigo_interno: "222100",
    nombre: "ARENA NEGRA MATE",
    descripcion_larga: "Porcelanato de aspecto pétreo en tono negro con motas grises. Acabado mate antideslizante clase C. Perfecto para terrazas, patios y zonas exteriores de alto tránsito.",
    categoria: "Porcelanato",
    subcategoria: "Mate",
    ancho: 45,
    largo: 45,
    espesor: 1.1,
    unidad_medida: "cm",
    color: "Negro",
    acabado: "Mate",
    material: "Porcelanato",
    uso: "Exterior",
    marca: "San Lorenzo",
    m2_por_caja: 1.215,
    piezas_por_caja: 6,
    peso: 28.0,
    precio_usd: 14.20,
    mostrar_precio: true,
    disponible: true,
    destacado: false,
    imagenes: [
      { url: "https://placehold.co/800x800/3a3a3a/e0e0e0?text=Arena+Negra", es_principal: true }
    ]
  },
  {
    id: "prod-012",
    codigo_interno: "222105",
    nombre: "ARENA HUESO MATE",
    descripcion_larga: "Porcelanato de exterior en tono hueso con textura arenosa. Acabado mate rugoso clase C antideslizante. Resistente a heladas, rayos UV y cambios bruscos de temperatura.",
    categoria: "Porcelanato",
    subcategoria: "Mate",
    ancho: 45,
    largo: 45,
    espesor: 1.1,
    unidad_medida: "cm",
    color: "Hueso",
    acabado: "Mate",
    material: "Porcelanato",
    uso: "Exterior",
    marca: "San Lorenzo",
    m2_por_caja: 1.215,
    piezas_por_caja: 6,
    peso: 28.0,
    precio_usd: 14.20,
    mostrar_precio: true,
    disponible: false,
    destacado: false,
    imagenes: [
      { url: "https://placehold.co/800x800/e8e0d8/4a4a4a?text=Arena+Hueso", es_principal: true }
    ]
  },
  {
    id: "prod-013",
    codigo_interno: "111050",
    nombre: "KONCEPT BLANCO BRILLO",
    descripcion_larga: "Cerámica de pared blanca con acabado brillante. Superficie lisa de fácil limpieza. Medidas clásicas para baños y cocinas. Precio económico sin sacrificar calidad.",
    categoria: "Cerámica",
    subcategoria: "Brillante",
    ancho: 20,
    largo: 30,
    espesor: 0.75,
    unidad_medida: "cm",
    color: "Blanco",
    acabado: "Brillante",
    material: "Cerámica",
    uso: "Pared",
    marca: "Cerámica Carabobo",
    m2_por_caja: 1.5,
    piezas_por_caja: 25,
    peso: 22.0,
    precio_usd: 7.80,
    mostrar_precio: true,
    disponible: true,
    destacado: false,
    imagenes: [
      { url: "https://placehold.co/800x800/fafafa/4a4a4a?text=Koncept+Blanco", es_principal: true }
    ]
  },
  {
    id: "prod-014",
    codigo_interno: "111055",
    nombre: "KONCEPT BEIGE MATE",
    descripcion_larga: "Cerámica de pared en tono beige con acabado mate. Textura sutil que no refleja la luz. Combina perfectamente con sanitarios de líneas modernas.",
    categoria: "Cerámica",
    subcategoria: "Mate",
    ancho: 20,
    largo: 30,
    espesor: 0.75,
    unidad_medida: "cm",
    color: "Beige",
    acabado: "Mate",
    material: "Cerámica",
    uso: "Pared",
    marca: "Cerámica Carabobo",
    m2_por_caja: 1.5,
    piezas_por_caja: 25,
    peso: 22.0,
    precio_usd: 7.80,
    mostrar_precio: true,
    disponible: true,
    destacado: false,
    imagenes: [
      { url: "https://placehold.co/800x800/f0ebe0/4a4a4a?text=Koncept+Beige", es_principal: true }
    ]
  },
  {
    id: "prod-015",
    codigo_interno: "111200",
    nombre: "DECORADO FLORAL AZUL",
    descripcion_larga: "Cerámica decorada con motivos florales en azul sobre blanco, estilo artesanal. Cada pieza tiene ligeras variaciones que le dan carácter único. Ideal para cenefas y acentos decorativos.",
    categoria: "Cerámica",
    subcategoria: "Decorado",
    ancho: 20,
    largo: 20,
    espesor: 0.8,
    unidad_medida: "cm",
    color: "Azul",
    acabado: "Brillante",
    material: "Cerámica",
    uso: "Pared",
    marca: "Cerámica Carabobo",
    m2_por_caja: 1.0,
    piezas_por_caja: 25,
    peso: 20.0,
    precio_usd: 9.50,
    mostrar_precio: true,
    disponible: true,
    destacado: false,
    imagenes: [
      { url: "https://placehold.co/800x800/f0f4ff/4a4a4a?text=Floral+Azul", es_principal: true }
    ]
  },
  {
    id: "prod-016",
    codigo_interno: "111500",
    nombre: "RÚSTICO TERRACOTA",
    descripcion_larga: "Cerámica de aspecto rústico en tono terracota. Acabado mate con bordes irregulares que evocan la cerámica artesanal mediterránea. Aporta calidez a terrazas y patios cubiertos.",
    categoria: "Cerámica",
    subcategoria: "Mate",
    ancho: 33,
    largo: 33,
    espesor: 0.85,
    unidad_medida: "cm",
    color: "Terracota",
    acabado: "Mate",
    material: "Cerámica",
    uso: "Piso",
    marca: "Incefa",
    m2_por_caja: 1.089,
    piezas_por_caja: 10,
    peso: 24.0,
    precio_usd: 11.20,
    mostrar_precio: true,
    disponible: true,
    destacado: false,
    imagenes: [
      { url: "https://placehold.co/800x800/c67a4a/fafafa?text=R%C3%BAstico+Terracota", es_principal: true }
    ]
  },
  {
    id: "prod-017",
    codigo_interno: "111600",
    nombre: "HIDRÁULICO TIPO VINTAGE",
    descripcion_larga: "Cerámica con diseño hidráulico tipo vintage en blanco, gris y negro. Patrones geométricos repetitivos. Retro moderna, ideal para pisos de cocina, baños y locales comerciales.",
    categoria: "Cerámica",
    subcategoria: "Decorado",
    ancho: 20,
    largo: 20,
    espesor: 0.8,
    unidad_medida: "cm",
    color: "Gris",
    acabado: "Mate",
    material: "Cerámica",
    uso: "Piso",
    marca: "Incefa",
    m2_por_caja: 1.0,
    piezas_por_caja: 25,
    peso: 21.0,
    precio_usd: 10.80,
    mostrar_precio: true,
    disponible: true,
    destacado: true,
    imagenes: [
      { url: "https://placehold.co/800x800/f0f0f0/4a4a4a?text=Hidr%C3%A1ulico+Vintage", es_principal: true }
    ]
  },
  {
    id: "prod-018",
    codigo_interno: "112100",
    nombre: "METRO BLANCO 10x20",
    descripcion_larga: "Cerámica de formato pequeño tipo metro, blanca con brillo. Acabado biselado de fábrica. Un clásico atemporal para cocinas y baños. Fácil de instalar y de limpiar.",
    categoria: "Cerámica",
    subcategoria: "Brillante",
    ancho: 10,
    largo: 20,
    espesor: 0.7,
    unidad_medida: "cm",
    color: "Blanco",
    acabado: "Brillante",
    material: "Cerámica",
    uso: "Pared",
    marca: "Cerámica Carabobo",
    m2_por_caja: 1.0,
    piezas_por_caja: 50,
    peso: 18.0,
    precio_usd: 6.50,
    mostrar_precio: true,
    disponible: true,
    destacado: false,
    imagenes: [
      { url: "https://placehold.co/800x800/fcfcfc/4a4a4a?text=Metro+Blanco", es_principal: true }
    ]
  },
  {
    id: "prod-019",
    codigo_interno: "112105",
    nombre: "METRO NEGRO MATE",
    descripcion_larga: "Cerámica formato metro en negro mate. Acabado sofisticado ideal para contrastes y detalles. Combina con blanco metro para diseños ajedrezados o cenefas.",
    categoria: "Cerámica",
    subcategoria: "Mate",
    ancho: 10,
    largo: 20,
    espesor: 0.7,
    unidad_medida: "cm",
    color: "Negro",
    acabado: "Mate",
    material: "Cerámica",
    uso: "Pared",
    marca: "Cerámica Carabobo",
    m2_por_caja: 1.0,
    piezas_por_caja: 50,
    peso: 18.0,
    precio_usd: 7.20,
    mostrar_precio: true,
    disponible: false,
    destacado: false,
    imagenes: [
      { url: "https://placehold.co/800x800/2a2a2a/e0e0e0?text=Metro+Negro", es_principal: true }
    ]
  },
  {
    id: "prod-020",
    codigo_interno: "113200",
    nombre: "PISO CERÁMICO TRAFALGAR",
    descripcion_larga: "Cerámica de piso de alto tránsito con diseño marmoleado en tonos grises y ocres. Acabado mate con microtextura antideslizante. Ideal para salas, comedores y pasillos.",
    categoria: "Cerámica",
    subcategoria: "Mate",
    ancho: 45,
    largo: 45,
    espesor: 0.9,
    unidad_medida: "cm",
    color: "Gris",
    acabado: "Mate",
    material: "Cerámica",
    uso: "Piso",
    marca: "San Lorenzo",
    m2_por_caja: 1.62,
    piezas_por_caja: 8,
    peso: 26.0,
    precio_usd: 9.90,
    mostrar_precio: true,
    disponible: true,
    destacado: false,
    imagenes: [
      { url: "https://placehold.co/800x800/d0ccc5/4a4a4a?text=Trafalgar", es_principal: true }
    ]
  },
  {
    id: "prod-021",
    codigo_interno: "300010",
    nombre: "PEGO BLANCO PREMIUM",
    descripcion_larga: "Pego blanco de alta adherencia para porcelanato y cerámica. Fórmula mejorada con polímeros que garantiza fijación superior en pisos y paredes. Apto para interiores y exteriores.",
    categoria: "Pego",
    subcategoria: "Polvo",
    ancho: 0,
    largo: 0,
    espesor: 0,
    unidad_medida: "mm",
    color: "Blanco",
    acabado: "N/A",
    material: "Cemento-Polímero",
    uso: "Ambos",
    marca: "Pegamax",
    m2_por_caja: 5,
    piezas_por_caja: 1,
    peso: 25,
    precio_usd: 8.50,
    mostrar_precio: true,
    disponible: true,
    destacado: false,
    imagenes: [
      { url: "https://placehold.co/800x800/fafafa/4a4a4a?text=Pego+Blanco", es_principal: true }
    ]
  },
  {
    id: "prod-022",
    codigo_interno: "300020",
    nombre: "PEGO GRIS ESTÁNDAR",
    descripcion_larga: "Pego gris de uso general para instalación de cerámica en pisos. Excelente rendimiento y trabajabilidad. Secado en 24 horas. Rendimiento aproximado de 5 m² por saco.",
    categoria: "Pego",
    subcategoria: "Polvo",
    ancho: 0,
    largo: 0,
    espesor: 0,
    unidad_medida: "mm",
    color: "Gris",
    acabado: "N/A",
    material: "Cemento-Polímero",
    uso: "Piso",
    marca: "Pegamax",
    m2_por_caja: 5,
    piezas_por_caja: 1,
    peso: 25,
    precio_usd: 6.90,
    mostrar_precio: true,
    disponible: true,
    destacado: false,
    imagenes: [
      { url: "https://placehold.co/800x800/d0d0d0/4a4a4a?text=Pego+Gris", es_principal: true }
    ]
  },
  {
    id: "prod-023",
    codigo_interno: "300030",
    nombre: "PEGO IMPERMEABLE PISCINAS",
    descripcion_larga: "Adhesivo impermeable de altas prestaciones para piscinas, fuentes y zonas de inmersión permanente. Resistente al cloro y a los químicos de tratamiento de agua.",
    categoria: "Pego",
    subcategoria: "Polvo",
    ancho: 0,
    largo: 0,
    espesor: 0,
    unidad_medida: "mm",
    color: "Blanco",
    acabado: "N/A",
    material: "Cemento-Polímero",
    uso: "Exterior",
    marca: "Weber",
    m2_por_caja: 4,
    piezas_por_caja: 1,
    peso: 25,
    precio_usd: 14.20,
    mostrar_precio: false,
    disponible: true,
    destacado: false,
    imagenes: [
      { url: "https://placehold.co/800x800/e8f4f8/4a4a4a?text=Pego+Piscinas", es_principal: true }
    ]
  },
  {
    id: "prod-024",
    codigo_interno: "300100",
    nombre: "PEGO PORCELÁNICO FLEX",
    descripcion_larga: "Adhesivo flexible de alta resistencia para porcelanato de gran formato y piedra natural. Ideal para instalación sobre sustratos con ligeros movimientos o sobre calefacción radiante.",
    categoria: "Pego",
    subcategoria: "Polvo",
    ancho: 0,
    largo: 0,
    espesor: 0,
    unidad_medida: "mm",
    color: "Gris",
    acabado: "N/A",
    material: "Cemento-Polímero",
    uso: "Ambos",
    marca: "Weber",
    m2_por_caja: 4,
    piezas_por_caja: 1,
    peso: 25,
    precio_usd: 16.50,
    mostrar_precio: true,
    disponible: true,
    destacado: true,
    imagenes: [
      { url: "https://placehold.co/800x800/d8d8d8/4a4a4a?text=Pego+Flex", es_principal: true }
    ]
  },
  {
    id: "prod-025",
    codigo_interno: "400010",
    nombre: "BOQUILLA BLANCA PREMIUM",
    descripcion_larga: "Boquilla cementicia blanca de alta calidad para juntas de 1 mm a 6 mm. Fórmula antimoho y antihongos. Fácil aplicación y limpieza. No mancha la superficie del revestimiento.",
    categoria: "Boquilla",
    subcategoria: "Polvo",
    ancho: 0,
    largo: 0,
    espesor: 0,
    unidad_medida: "mm",
    color: "Blanco",
    acabado: "N/A",
    material: "Cemento",
    uso: "Ambos",
    marca: "Pegamax",
    m2_por_caja: 15,
    piezas_por_caja: 1,
    peso: 1,
    precio_usd: 3.50,
    mostrar_precio: true,
    disponible: true,
    destacado: false,
    imagenes: [
      { url: "https://placehold.co/800x800/fafafa/4a4a4a?text=Boquilla+Blanca", es_principal: true }
    ]
  },
  {
    id: "prod-026",
    codigo_interno: "400020",
    nombre: "BOQUILLA GRIS CEMENTO",
    descripcion_larga: "Boquilla cementicia gris para juntas de 2 mm a 12 mm. Acabado uniforme y durable. Resistente al tránsito peatonal intenso. Secado rápido en 2 horas.",
    categoria: "Boquilla",
    subcategoria: "Polvo",
    ancho: 0,
    largo: 0,
    espesor: 0,
    unidad_medida: "mm",
    color: "Gris",
    acabado: "N/A",
    material: "Cemento",
    uso: "Piso",
    marca: "Pegamax",
    m2_por_caja: 12,
    piezas_por_caja: 1,
    peso: 1,
    precio_usd: 2.90,
    mostrar_precio: true,
    disponible: true,
    destacado: false,
    imagenes: [
      { url: "https://placehold.co/800x800/c0c0c0/4a4a4a?text=Boquilla+Gris", es_principal: true }
    ]
  },
  {
    id: "prod-027",
    codigo_interno: "400100",
    nombre: "BOQUILLA EPÓXICA GRIS PLATA",
    descripcion_larga: "Boquilla epóxica bicomponente de altas prestaciones en tono gris plata. Impermeable, resistente a químicos, ácidos y manchas. Ideal para cocinas industriales, hospitales y laboratorios.",
    categoria: "Boquilla",
    subcategoria: "Epóxica",
    ancho: 0,
    largo: 0,
    espesor: 0,
    unidad_medida: "mm",
    color: "Gris Plata",
    acabado: "N/A",
    material: "Epoxi",
    uso: "Ambos",
    marca: "Weber",
    m2_por_caja: 10,
    piezas_por_caja: 1,
    peso: 2.5,
    precio_usd: 22.80,
    mostrar_precio: false,
    disponible: false,
    destacado: false,
    imagenes: [
      { url: "https://placehold.co/800x800/a8a8a8/ffffff?text=Boquilla+Ep%C3%B3xica", es_principal: true }
    ]
  },
  {
    id: "prod-028",
    codigo_interno: "500010",
    nombre: "CRUCETAS 2mm (BOLSA 200u)",
    descripcion_larga: "Crucetas espaciadoras de 2 mm para colocación de cerámica y porcelanato. Bolsa de 200 unidades. Plástico reciclable de alta resistencia. No se deforman al presionar.",
    categoria: "Accesorios",
    subcategoria: "Espaciadores",
    ancho: 0,
    largo: 0,
    espesor: 0,
    unidad_medida: "mm",
    color: "Blanco",
    acabado: "N/A",
    material: "Plástico",
    uso: "Ambos",
    marca: "Genérico",
    m2_por_caja: 0,
    piezas_por_caja: 200,
    peso: 0.2,
    precio_usd: 1.80,
    mostrar_precio: true,
    disponible: true,
    destacado: false,
    imagenes: [
      { url: "https://placehold.co/800x800/e0e0e0/4a4a4a?text=Crucetas+2mm", es_principal: true }
    ]
  },
  {
    id: "prod-029",
    codigo_interno: "500020",
    nombre: "LLANA DENTADA 8mm",
    descripcion_larga: "Llana dentada profesional de 8 mm para aplicación de pego en pisos. Mango ergonómico antideslizante. Hoja de acero templado de 25 cm de ancho.",
    categoria: "Accesorios",
    subcategoria: "Herramientas",
    ancho: 0,
    largo: 0,
    espesor: 0,
    unidad_medida: "mm",
    color: "Gris",
    acabado: "N/A",
    material: "Acero",
    uso: "Ambos",
    marca: "Genérico",
    m2_por_caja: 0,
    piezas_por_caja: 1,
    peso: 0.5,
    precio_usd: 5.50,
    mostrar_precio: true,
    disponible: true,
    destacado: false,
    imagenes: [
      { url: "https://placehold.co/800x800/c8c8c8/4a4a4a?text=Llana+Dentada", es_principal: true }
    ]
  },
  {
    id: "prod-030",
    codigo_interno: "500030",
    nombre: "PERFIL ESQUINERO ALUMINIO",
    descripcion_larga: "Perfil esquinero de aluminio anodizado para protección de cantos en escaleras y esquinas de revestimiento. Largo 2.70 m. Acabado plata mate. Incluye ala de anclaje perforada.",
    categoria: "Accesorios",
    subcategoria: "Perfiles",
    ancho: 1.2,
    largo: 270,
    espesor: 0.2,
    unidad_medida: "cm",
    color: "Gris Plata",
    acabado: "N/A",
    material: "Aluminio",
    uso: "Ambos",
    marca: "Genérico",
    m2_por_caja: 0,
    piezas_por_caja: 10,
    peso: 0.8,
    precio_usd: 4.20,
    mostrar_precio: true,
    disponible: false,
    destacado: false,
    imagenes: [
      { url: "https://placehold.co/800x800/d0d0d0/4a4a4a?text=Perfil+Aluminio", es_principal: true }
    ]
  }
];

if (typeof window !== 'undefined') {
  window.TASAS_CAMBIO = TASAS_CAMBIO;
  window.PRODUCTOS = PRODUCTOS;
}
